# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:

    sportuser.form.registration:
        class: SPORT\UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: sport_user_registration }
    
    admin.salle:
        class: SPORT\SanteBundle\Admin\SalleAdmin
        arguments: [~, SPORT\SanteBundle\Entity\Salle, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Salle }
    admin.seance:
        class: SPORT\SanteBundle\Admin\SeanceAdmin
        arguments: [~, SPORT\SanteBundle\Entity\Seance, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Seance }
    admin.creneau:
        class: SPORT\SanteBundle\Admin\CreneauAdmin
        arguments: [~, SPORT\SanteBundle\Entity\Creneau, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Creneau }
    
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
