<?php

namespace Proxies\__CG__\SPORT\SanteBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Salle extends \SPORT\SanteBundle\Entity\Salle implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'SPORT\\SanteBundle\\Entity\\Salle' . "\0" . 'id', '' . "\0" . 'SPORT\\SanteBundle\\Entity\\Salle' . "\0" . 'nomSalle', '' . "\0" . 'SPORT\\SanteBundle\\Entity\\Salle' . "\0" . 'adresseSalle', '' . "\0" . 'SPORT\\SanteBundle\\Entity\\Salle' . "\0" . 'villeSalle', '' . "\0" . 'SPORT\\SanteBundle\\Entity\\Salle' . "\0" . 'cpSalle', '' . "\0" . 'SPORT\\SanteBundle\\Entity\\Salle' . "\0" . 'latitude', '' . "\0" . 'SPORT\\SanteBundle\\Entity\\Salle' . "\0" . 'longitude', '' . "\0" . 'SPORT\\SanteBundle\\Entity\\Salle' . "\0" . 'seances'];
        }

        return ['__isInitialized__', '' . "\0" . 'SPORT\\SanteBundle\\Entity\\Salle' . "\0" . 'id', '' . "\0" . 'SPORT\\SanteBundle\\Entity\\Salle' . "\0" . 'nomSalle', '' . "\0" . 'SPORT\\SanteBundle\\Entity\\Salle' . "\0" . 'adresseSalle', '' . "\0" . 'SPORT\\SanteBundle\\Entity\\Salle' . "\0" . 'villeSalle', '' . "\0" . 'SPORT\\SanteBundle\\Entity\\Salle' . "\0" . 'cpSalle', '' . "\0" . 'SPORT\\SanteBundle\\Entity\\Salle' . "\0" . 'latitude', '' . "\0" . 'SPORT\\SanteBundle\\Entity\\Salle' . "\0" . 'longitude', '' . "\0" . 'SPORT\\SanteBundle\\Entity\\Salle' . "\0" . 'seances'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Salle $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomSalle($nomSalle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomSalle', [$nomSalle]);

        return parent::setNomSalle($nomSalle);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomSalle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomSalle', []);

        return parent::getNomSalle();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresseSalle($adresseSalle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresseSalle', [$adresseSalle]);

        return parent::setAdresseSalle($adresseSalle);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresseSalle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresseSalle', []);

        return parent::getAdresseSalle();
    }

    /**
     * {@inheritDoc}
     */
    public function setVilleSalle($villeSalle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVilleSalle', [$villeSalle]);

        return parent::setVilleSalle($villeSalle);
    }

    /**
     * {@inheritDoc}
     */
    public function getVilleSalle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVilleSalle', []);

        return parent::getVilleSalle();
    }

    /**
     * {@inheritDoc}
     */
    public function setCpSalle($cpSalle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCpSalle', [$cpSalle]);

        return parent::setCpSalle($cpSalle);
    }

    /**
     * {@inheritDoc}
     */
    public function getCpSalle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCpSalle', []);

        return parent::getCpSalle();
    }

    /**
     * {@inheritDoc}
     */
    public function addSeance(\SPORT\SanteBundle\Entity\Seance $seance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSeance', [$seance]);

        return parent::addSeance($seance);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSeance(\SPORT\SanteBundle\Entity\Seance $seance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSeance', [$seance]);

        return parent::removeSeance($seance);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeances()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeances', []);

        return parent::getSeances();
    }

    /**
     * {@inheritDoc}
     */
    public function setLatitude($latittude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLatitude', [$latittude]);

        return parent::setLatitude($latittude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLatitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatitude', []);

        return parent::getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongitude($longitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongitude', [$longitude]);

        return parent::setLongitude($longitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongitude', []);

        return parent::getLongitude();
    }

}
