services:
    tva:
        class: SPORT\LocationBundle\Twig\Extension\TvaExtension
        tags: 
           - { name: twig.extension }
    redirectionListener:
        class: SPORT\LocationBundle\Listener\RedirectionListener
        arguments:  ["@service_container", "@session"]
          
        tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
#    sport_location.example:
#        class: SPORT\LocationBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
