<?php

namespace SPORT\LocationBundle\Repository;

/**
 * AdresseUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdresseUserRepository extends \Doctrine\ORM\EntityRepository
{
}
