<?php

namespace SPORT\SanteBundle\Repository;

/**
 * AbonnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbonnementRepository extends \Doctrine\ORM\EntityRepository {

    function findAbonnementByUser($id) {
        $date = new \DateTime();
        $qb = $this->createQueryBuilder('Abonnement')
                ->innerJoin('Abonnement.user', 'user')
                ->addSelect('user')
                ->where('Abonnement.datefin>=?1 and user.id=?2')
                ->setParameters(array(1 => $date, 2 => $id));
        // Enfin, on retourne le résultat
        $resul = $qb
                ->getQuery()
                ->getOneOrNullResult();


        return $resul;
    }

}
