<?php

namespace SPORT\SanteBundle\Repository;

use SPORT\SanteBundle\Entity\Seance;

/**
 * CreneauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreneauRepository extends \Doctrine\ORM\EntityRepository
{
    function findSeanceById($id) {
        $qb = $this->createQueryBuilder('Seance')
                ->where('Seance.id=?1')
                ->setParameters(array(1 => $id));
        // Enfin, on retourne le résultat
        $resul=$qb
                        ->getQuery()
                        ->getResult();
                
      
        return $resul;
    }
    
   
    
    
    function  findByCoursByseance($id){
            
       
		$seance= $this
                ->findSeanceById($id);
                
                $qb = $this->createQueryBuilder('Creneau')
                ->innerJoin('Creneau.seance', 'se')
                ->addSelect('se')
                ->innerJoin('se.salle', 'sa')
                ->addSelect('sa')
                ->where('se.id=?1')
               // ->orderBy('Seance.dateSeance', 'ASC')
                ->setParameters(array(1 => $id));
        // Enfin, on retourne le résultat
        return $qb
                        ->getQuery()
                        ->getResult();
                
                
		
}
}
?>